config/routes.rb
Rails.application.routes.draw do
  get "person" => "person"
  get "location" => "location"
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def dataNotFound
        redirect_back_or_to root_path
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require "csv"

    @skip = (params["skip"].presence || 0).to_i
    @take = (params["take"].presence || 10).to_i

    csvRows = CSV.parse(File.read("data/data.csv"), headers: true, header_converters: lambda { |header| header.strip })

    @data = []

    csvRows.each do |row|
      name = row["first_name"].strip + " " + row["last_name"].strip
      address = row["address"].strip
      @data << {"name" => name, "address" => address}
    end

    @maxLength = @data.length
    @numPages = (@maxLength / @take.to_f).ceil

    if @skip >= @maxLength || @skip < 0
      @skip = 0
    end

    @data = @data.slice(@skip, @take)
  end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
    def location
      require "net/http"
      
      geocodeApiUrl = "https://geocoding.geo.census.gov/geocoder/geographies/onelineaddress?address=%s&benchmark=Public_AR_Census2020&vintage=Census2020_Census2020&layers=10&format=json"

      censusVariables = [
        "NAME",  
        "DP02_0124E",   # Total Population    
        "DP03_0062E",   # Median Income
        "DP03_0119PE",  # % Families and People Whose Income in the past 12 months is below the poverty level
        "DP02_0067PE",  # Educational Attainment (25 years and over, high school graduate or higher, %)
        "DP02_0016E",   # Average Household Size
        "DP02_0007E",   # Single Male Householder With Children
        "DP02_0011E",   # Single Female Householder With Children
        "DP02_0114PE",  # Language Spoken At Home Other Than English (5 years and over, %)
        "DP02_0154PE",  # Households With Internet Subscription (%)
        "DP03_0009PE",  # Unemployment Rate (%)
      ]
      indexMap = createIndexMap(censusVariables)

      censusApiUrl = "https://api.census.gov/data/2022/acs/acs5/profile?get=" + censusVariables.join(",") + "&for=tract:%s&in=state:%s county:%s"

      @locationInfo = {
        "censusBlockName" => "",
        "totalPop" => 0,
        "medianIncome" => 0,
        "incomePoverty" => 0,
        "education" => 0,
        "avgHouseholdSize" => 0,
        "singleMaleWithChildren" => 0,
        "singleFemaleWithChildren" => 0,
        "homeLanguageNotEnglish" => 0,
        "internetSubscription" => 0,
        "unemploymentRate" => 0
      }

      @query = params["q"]
      url = URI.parse(geocodeApiUrl % [@query])
      result = Net::HTTP.get(url)

      resultDecoded = ActiveSupport::JSON.decode(result)
      addressMatch = resultDecoded["result"]["addressMatches"][0]
      if addressMatch.blank?
        dataNotFound
      else
        censusBlock = addressMatch["geographies"]["Census Blocks"][0]
        censusResult = Net::HTTP.get(URI(censusApiUrl % [censusBlock["TRACT"], censusBlock["STATE"], censusBlock["COUNTY"]]))

        if censusResult
          censusResultDecoded = ActiveSupport::JSON.decode(censusResult)
          censusData = censusResultDecoded[1]

          if censusData
            @locationInfo["censusBlockName"] = censusData[indexMap["NAME"]].gsub(";", ",")
            @locationInfo["totalPop"] = censusData[indexMap["DP02_0124E"]].to_i
            @locationInfo["medianIncome"] = censusData[indexMap["DP03_0062E"]].to_i
            @locationInfo["incomePoverty"] = censusData[indexMap["DP03_0119PE"]].to_f
            @locationInfo["education"] = censusData[indexMap["DP02_0067PE"]].to_f
            @locationInfo["avgHouseholdSize"] = censusData[indexMap["DP02_0016E"]].to_f
            @locationInfo["singleMaleWithChildren"] = censusData[indexMap["DP02_0007E"]].to_i
            @locationInfo["singleFemaleWithChildren"] = censusData[indexMap["DP02_0011E"]].to_i
            @locationInfo["homeLanguageNotEnglish"] = censusData[indexMap["DP02_0114PE"]].to_f
            @locationInfo["internetSubscription"] = censusData[indexMap["DP02_0154PE"]].to_f
            @locationInfo["unemploymentRate"] = censusData[indexMap["DP03_0009PE"]].to_f
          end
        end
      end
    end

    # Index mapping of variables to allow use of variable name instead of keeping track of indexes
    def createIndexMap(arr)
      indexMap = {}

      arr.each_with_index do |key, index|
        indexMap[key] = index
      end

      return indexMap
    end
  end

app/controllers/person_controller.rb
class PersonController < ApplicationController
    def person
      require "faker"
      
      @query = params["q"]

      if @query.blank?
        dataNotFound
      else
        num = generateNumberFromName(@query)
        Faker::Config.random = Random.new(num)
  
        # In a real setting, this data would be populated via some public register record in a database or similar
        @personInfo = {
          "education" => Faker::Demographic.educational_attainment,
          "maritalStatus" => Faker::Demographic.marital_status,
          "fieldOfWork" => Faker::Job.field,
          "jobTitle" => Faker::Job.title,
          "employmentType" => Faker::Job.employment_type,
          "vehicle" => Faker::Vehicle.make_and_model
        }
      end
    end

    # Generates number from name string to use with faker for deterministic randomness - demo purposes only
    def generateNumberFromName(name)
      numberString = ""
      nameArr = name.split(" ")

      nameArr.each do |nameSegment|
        nameSegment.each_char.with_index do |char, index|
          break if index >= 3
          numberString += char.ord.to_s
        end
      end

      return numberString.to_i
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<br />
<br />
<br />

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to "DataStatus", root_path, class: "navbar-brand" %>
  </div>
</nav>

app/views/home/index.html.erb
<h1>List of People and Addresses</h1>
<br/>
<table class="table table-striped table-bordered table-hover">
    <thead class="table-dark">
        <tr>
            <th>Name</th>
            <th>Address</th>
        </tr>
    </thead>

    <tbody>
        <% @data.each do |row| %>
            <tr>
                <td><%= link_to row["name"], person_path(q: row["name"]), class: "link-dark text-decoration-none link-opacity-75-hover" %></td>
                <td><%= link_to row["address"], location_path(q: row["address"]), class: "link-dark text-decoration-none link-opacity-75-hover" %></td>
            </tr>
        <% end %>
    </tbody>
</table>

  <ul class="pagination">
    <li class="page-item <%= @skip <= 0 ? "disabled" : "" %>"><%= link_to "Previous", root_path(:skip => @skip - @take, :take => @take), class: "page-link" %></li>
    <% @numPages.times do |i| %>
        <li class="page-item <%= i == @skip / @take ? "active" : "" %>"><%= link_to i + 1, root_path(:skip => i * @take, :take => @take), class: "page-link" %></li>
    <% end %>
    <li class="page-item <%= @skip + @take >= @maxLength ? "disabled" : "" %>"><%= link_to "Next", root_path(:skip => @skip + @take, :take => @take), class: "page-link" %></li>
  </ul>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <title>DataStatus</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <%= render "home/header" %>
    <div class="container">
      <br/>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <%= render "home/footer" %>
  </body>
</html>

app/views/location/location.html.erb
<div class="container-fluid bg-light p-5 rounded">
    <div class="container p-5">
        <h1 class="display-6 fw-bold"><%= @query %></h1>
        <p class="lead"><%= @locationInfo["censusBlockName"] %></p>
        <hr class="my-4">

        <form class="row g-3">
            <div class="col-12">
                <label class="form-label fw-bold">Total Population</label>
                <input type="text" class="form-control bg-white" disabled readonly value="<%= @locationInfo["totalPop"] %>">
            </div>

            <div class="col-12 mt-5">
                <label class="form-label fw-bold">Educational Attainment (25 years and over; high school graduate or higher)</label>
                <input type="text" class="form-control bg-white" disabled readonly value="<%= @locationInfo["education"] %>%">
            </div>

            <div class="col-lg-4  mt-5">
                <label class="form-label fw-bold">Median Income</label>
                <input type="text" class="form-control bg-white" disabled readonly value="$<%= @locationInfo["medianIncome"] %>">
            </div>
            <div class="col-lg-4  mt-5">
                <label class="form-label fw-bold">Income Below the Poverty Line</label>
                <input type="text" class="form-control bg-white" disabled readonly value="<%= @locationInfo["incomePoverty"] %>%">
            </div>
            <div class="col-lg-4  mt-5">
                <label class="form-label fw-bold">Unemployment Rate</label>
                <input type="text" class="form-control bg-white" disabled readonly value="<%= @locationInfo["unemploymentRate"] %>%">
            </div>

            <div class="col-lg-4  mt-5">
                <label class="form-label fw-bold">Average Household Size</label>
                <input type="text" class="form-control bg-white" disabled readonly value="<%= @locationInfo["avgHouseholdSize"] %>">
            </div>
            <div class="col-lg-4  mt-5">
                <label class="form-label fw-bold">Single Males with Children</label>
                <input type="text" class="form-control bg-white" disabled readonly value="<%= @locationInfo["singleMaleWithChildren"] %>">
            </div>
            <div class="col-lg-4  mt-5">
                <label class="form-label fw-bold">Single Females with Children</label>
                <input type="text" class="form-control bg-white" disabled readonly value="<%= @locationInfo["singleFemaleWithChildren"] %>">
            </div>

            <div class="col-lg-6  mt-5">
                <label class="form-label fw-bold">Spoken Language at Home not English</label>
                <input type="text" class="form-control bg-white" disabled readonly value="<%= @locationInfo["homeLanguageNotEnglish"] %>%">
            </div>
            <div class="col-lg-6  mt-5">
                <label class="form-label fw-bold">Households with an Internet Subscription</label>
                <input type="text" class="form-control bg-white" disabled readonly value="<%= @locationInfo["internetSubscription"] %>%">
            </div>
        </form>

        <br/><br/>
        <%= button_to "Back", root_path, class: "btn btn-dark", :method => :get %>
    </div>
</div>

app/views/person/person.html.erb
<div class="container-fluid bg-light p-5 rounded">
    <div class="container p-5">
        <h1 class="display-6 fw-bold"><%= @query %></h1>
        <hr class="my-4">

        <form class="row g-3">
            <div class="col-12">
                <label class="form-label fw-bold">Marital Status</label>
                <input type="text" class="form-control bg-white" disabled readonly value="<%= @personInfo["maritalStatus"] %>">
            </div>

            <div class="col-12 mt-5">
                <label class="form-label fw-bold">Educational Attainment</label>
                <input type="text" class="form-control bg-white" disabled readonly value="<%= @personInfo["education"] %>">
            </div>

            <div class="col-lg-4  mt-5">
                <label class="form-label fw-bold">Field of Work</label>
                <input type="text" class="form-control bg-white" disabled readonly value="<%= @personInfo["fieldOfWork"] %>">
            </div>
            <div class="col-lg-4  mt-5">
                <label class="form-label fw-bold">Job Title</label>
                <input type="text" class="form-control bg-white" disabled readonly value="<%= @personInfo["jobTitle"] %>">
            </div>
            <div class="col-lg-4  mt-5">
                <label class="form-label fw-bold">Employment Type</label>
                <input type="text" class="form-control bg-white" disabled readonly value="<%= @personInfo["employmentType"] %>">
            </div>

            <div class="col-12 mt-5">
                <label class="form-label fw-bold">Vehicle</label>
                <input type="text" class="form-control bg-white" disabled readonly value="<%= @personInfo["vehicle"] %>">
            </div>
        </form>

        <br/><br/>
        <%= button_to "Back", root_path, class: "btn btn-dark", :method => :get %>
    </div>
</div>